language: android

notifications:
  email: false
  slack:
    secure: Hymc0SLJvbcEXs4aejGgA6qDWuoSvnot6FPFyCwD9NXk79MhpxxBUGWahjAUxJI+7uVlMB/N3MEmX7/7HDGo9oe5X/uG/VAzBO2CklvoW1JZF7Ty4DIv1cvPN1o3JWzn30AMJdFwgqIewJyidyRx5y1jid3W2vbzZSDLpTr3PqZT4jped+2MD9eXVWKW3iQwvpZH/D9hpO0Pz/ASRkO2qfDjHPC0dpPskPARx6DYOySqcKUOsuOJqTdp+GZzxKRz4Djq7TNnJ8CD0lekCpbGEt6F36hSx0Ca5Q0nT9Aw28yBcMYDWlp4rbKoUWTgf6xQN0mxcnM8phDJnzNbfUQgQ9C6fsb02hE910t/jrqu6AMRfMVhDiaHCAuTJH0KcbHBHLCwsTCFSZdrpjjSuJmAwTlBT+OYd6QJMY82CRKiV9iYVnajfE16yh6ZIfpndxCkXDL6GcBJNiYOU7QKS7ROYn02FNh5ESR0X5DT4gVBCNDZavA8ZoAtNjTN+Hg0TIQ579jTUAGki30wvSP0IRUEeH+fsxpUocuYcbYyzatiEPrdcxuKZC0iBNwQy53a6g10obd2s2T/8lhbcyFRPNEC2rXthp/sgAGv6DsnsepoTaL4XPxy+sCM5LrhJ2GWaKMTjElW69k00XW2f++BEan1SllG4kM7rU/px94+zeIMm/g=

sudo: false

jdk:
- openjdk7

env:
  global:
  # Add some wait time for the emulator
  - ADB_INSTALL_TIMEOUT=5

android:
  components:
  - tools
  - build-tools-24.0.0
  # Needed for the app itself
  - android-24
  # Needed for volley
  - android-22
  - build-tools-23.0.3
  # Extra tools
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services
  # Emulator image
  - sys-img-x86-android-24
  licences:
  # Accept all licences
  - ".+"

before_script:
- echo no | android create avd --force -n test -t android-24 --abi x86
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- android list target
- "./gradlew connectedAndroidTest"

# Cache setup
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
